# Generated by Django 3.2.5 on 2021-09-04 16:42

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='users_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('task_url', models.SlugField(blank=True, null=True)),
                ('task_creation_date', models.DateTimeField(auto_now_add=True)),
                ('task_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_task_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospective_student_tasks_list', to='immi_user_analysis.users_task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospective_student_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
