# Generated by Django 3.2.5 on 2021-09-07 04:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('immi_user_analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users_task',
            new_name='UserTask',
        ),
        migrations.RenameModel(
            old_name='user_task_status',
            new_name='UserTaskStatus',
        ),
    ]
