# Generated by Django 3.2.5 on 2021-09-04 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='forum_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('post_url', models.SlugField(blank=True, null=True)),
                ('post_discription', models.TextField(max_length=1500)),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('like', models.ManyToManyField(related_name='blogs_post', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='forum_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_body', models.TextField()),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('all_like', models.ManyToManyField(related_name='comment_like', to=settings.AUTH_USER_MODEL)),
                ('blogs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_comments', to='immi_fourm.forum_post')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_comments_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='bookmarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks_blogs', to='immi_fourm.forum_post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
