# Generated by Django 3.2.5 on 2021-09-07 02:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('immi_fourm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='forum_comment',
            new_name='ForumComment',
        ),
        migrations.RenameModel(
            old_name='forum_post',
            new_name='ForumPost',
        ),
        migrations.RenameField(
            model_name='forumpost',
            old_name='post_discription',
            new_name='post_description',
        ),
    ]
