# Generated by Django 3.2.5 on 2021-09-07 03:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('immi_message', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='group_message',
            new_name='GroupMessage',
        ),
        migrations.RenameModel(
            old_name='groups_list',
            new_name='GroupsList',
        ),
        migrations.RenameModel(
            old_name='single_message',
            new_name='SingleMessage',
        ),
    ]
